# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-OSCAR
version:      0.04
version_from: lib/POE/Component/OSCAR.pm
installdirs:  site
requires:
    Filter::Template:              1.02
    Net::OSCAR:                    0.62
    POE:                           0.28
    Time::HiRes:                   0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
